# Generated by Django 5.1.6 on 2025-03-10 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adc_value', models.IntegerField()),
                ('estimated_capacity', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(default='ESP32', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
