# Generated by Django 5.1.6 on 2025-03-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitordata',
            options={},
        ),
        migrations.RemoveField(
            model_name='capacitordata',
            name='device_id',
        ),
    ]
