# Generated by Django 5.1.6 on 2025-03-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0002_alter_capacitordata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitordata',
            name='estimated_capacity',
        ),
    ]
