# Generated by Django 5.1.6 on 2025-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor_data', '0003_remove_capacitordata_estimated_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitordata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Capacitor Data', 'verbose_name_plural': 'Capacitor Data'},
        ),
        migrations.AddField(
            model_name='capacitordata',
            name='estimated_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
